# Generated by Django 4.2.20 on 2025-03-18 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'A: Infracciones al conductor de un vehículo no automotor o de tracción animal'), ('B', 'B: Infracciones al conductor y/o propietario de un vehículo automotor'), ('C', 'C: Infracciones al conductor y/o propietario de un vehículo automotor'), ('D', 'D: Infracciones al conductor y/o propietario de un vehículo automotor'), ('E', 'E: Infracciones al conductor y/o propietario de un vehículo automotor'), ('FF', 'FF: Conducir en estado de embriaguez'), ('F', 'F: Infracciones al peatón'), ('G', 'G: Infracciones comparendos educativos'), ('H', 'H: Infracciones al conductor, pasajero o peatón'), ('I', 'I: Infracciones de sanciones pecuniarias de diferentes montos'), ('J', 'J: Otras infracciones de competencia de las autoridades de tránsito')], max_length=2, verbose_name='Categoría')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('fine', models.IntegerField(verbose_name='Multa en SMDLV')),
            ],
            options={
                'verbose_name': 'Infracción',
                'verbose_name_plural': 'Infracciones',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(choices=[(1, 'Agente de tránsito'), (2, 'Cámara de seguridad')], verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación')),
                ('infraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='violations.infraction')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officers.officer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Comparendo',
                'verbose_name_plural': 'Comparendos',
            },
        ),
    ]
