# Generated by Django 4.2.20 on 2025-03-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraction',
            name='impound',
            field=models.BooleanField(default=False, verbose_name='Inmovilización'),
        ),
    ]
