# Generated by Django 4.2.20 on 2025-03-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_infraction_impound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraction',
            name='code',
            field=models.CharField(max_length=4, unique=True, verbose_name='Código'),
        ),
    ]
