# Generated by Django 4.2.20 on 2025-03-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Agente'), (2, 'Supervisor')], verbose_name='Tipo de funcionario')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Oficial',
                'verbose_name_plural': 'Oficiales de tránsito',
            },
        ),
    ]
