# Generated by Django 4.2.20 on 2025-03-18 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Automóvil'), (2, 'Motocicleta'), (3, 'Vehículo pesado')], verbose_name='Tipo de vehículo')),
                ('license_plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('brand', models.CharField(max_length=255, verbose_name='Marca')),
                ('model', models.CharField(max_length=255, verbose_name='Modelo')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('since', models.DateField(verbose_name='Fecha de registro')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
