# Generated by Django 4.2.20 on 2025-03-18 02:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.IntegerField(choices=[(1, 'Persona Natural'), (2, 'Persona Jurídica')], verbose_name='Tipo de persona')),
                ('identification_type', models.IntegerField(choices=[(1, 'Cédula de ciudadanía'), (2, 'NIT'), (3, 'Pasaporte')], verbose_name='Tipo de identificación')),
                ('identification_number', models.CharField(max_length=20, unique=True, verbose_name='Número de identificación')),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
